### ISSUE TITLE
Support empty prefix

### ISSUE THREAD

**Issue by roberth** [nix-community/nixdoc#119]
I'm trying to write a `pkgs.moduleSystem` library (for the option docs generating part, replacing `nixosOptionsDoc`), but passing that as a prefix results in rather long titles.
I figured `--prefix ""` would do the right thing, but that still generates a "separator", resulting in headers like `.rendering`, which isn't quite right.
The default prefix is `lib`, not an internal representation for "no prefix at all", unfortunately.

I propose that `--prefix ""` will be the accepted syntax for prefixing nothing at all; not even the separating `.`.

Context:
- https://github.com/NixOS/nixpkgs/pull/305847

**Comment by infinisil** [comment]
Sounds reasonable to me, PR appreciated!
