### ISSUE TITLE
Section headings from comments at top of files

### ISSUE THREAD

**Issue by tazjin** [nix-community/nixdoc#19]
Currently sections (i.e. the "groups" of functions, `strings`, `lists` etc.) generated by `nixdoc` don't have any descriptions other than what the user specifies on the CLI.

Some files (for example [lib/debug.nix](https://github.com/NixOS/nixpkgs/blob/master/lib/debug.nix)) have multi-line comments at the beginning that could be interpreted as section headings.

Implementation wise, the `rnix` parser will probably attach those as `meta` to the very first AST node which should be relatively easy to check for.

**Comment by fricklerhandwerk** [comment]
@zmitchell is interested to pick this up

**Comment by tazjin** [comment]
Note that before adding any complex features like this depending on parser output, the parser should be upgraded. nixdoc is using a very old version of rnix, and the API has nothing to do with the current one anymore - the longer that isn't done, the harder it will be eventually if more things are built on the old API.

**Comment by infinisil** [comment]
This is now implemented with #70!
